from bazi_spider.customer import Customer


class Test(object):
    def __init__(self):
        pass

    @staticmethod
    def print_simple_info(customer: Customer):
        print("基本信息")
        print("==========================================")
        print(customer.name)
        print("男" if customer.sex == "1" else "女")
        print("%s/%s/%s/%s:%s" % (customer.year, customer.month, customer.day, customer.hour, customer.minute))
        print("%s-%s-%s" % (customer.province, customer.city, customer.area))
        print("\n\n四柱")
        print("==========================================")
        print(customer.year_pillar)
        print(customer.month_pillar)
        print(customer.day_pillar)
        print(customer.hour_pillar)
        print("\n\n主星")
        print("==========================================")
        print(customer.year_main_star)
        print(customer.month_main_star)
        print(customer.day_main_star)
        print(customer.hour_main_star)
        print("\n\n藏干")
        print("==========================================")
        print(customer.year_hidden_gan)
        print(customer.month_hidden_gan)
        print(customer.day_hidden_gan)
        print(customer.hour_hidden_gan)
        print("\n\n星运")
        print("==========================================")
        print(customer.year_star_yun)
        print(customer.month_star_yun)
        print(customer.day_star_yun)
        print(customer.hour_star_yun)
        print("\n\n副星")
        print("==========================================")
        print(customer.year_vice_star)
        print(customer.month_vice_star)
        print(customer.day_vice_star)
        print(customer.hour_vice_star)
        print("\n\n自坐")
        print("==========================================")
        print(customer.year_self_loc)
        print(customer.month_self_loc)
        print(customer.day_self_loc)
        print(customer.hour_self_loc)
        print("\n\n空亡")
        print("==========================================")
        print(customer.year_entity_disappear)
        print(customer.month_entity_disappear)
        print(customer.day_entity_disappear)
        print(customer.hour_entity_disappear)
        print("\n\n纳音")
        print("==========================================")
        print(customer.year_include_sounds)
        print(customer.month_include_sounds)
        print(customer.day_include_sounds)
        print(customer.hour_include_sounds)
        print("\n\n神煞")
        print("==========================================")
        print(customer.year_spirits)
        print(customer.month_spirits)
        print(customer.day_spirits)
        print(customer.hour_spirits)
